import { Badge } from '@/types';

export const badgeToAssetId: Partial<Record<Badge, string | number>> = {
  [Badge.KM_WALKED]: 1,
  [Badge.DEX_GEN_1]: 2,
  [Badge.CAUGHT_POKEMON]: 3,
  [Badge.EVOLVED]: 5,
  [Badge.HATCHED]: 6,
  [Badge.STOPS_SPUN]: 8,
  [Badge.UNIQUE_STOPS_SPUN]: 9,
  [Badge.XL_KARPS]: 11,
  [Badge.GYM_BATTLES_WON]: 13,
  [Badge.TRAININGS_WON]: 14,
  [Badge.XS_RATS]: 36,
  [Badge.TINY_POKEMON_CAUGHT]: 1, //need to update this badge
  [Badge.JUMBO_POKEMON_CAUGHT]: 1, //need to update this badge
  [Badge.VIVILLON]: 1, //need to update this badge
  [Badge.PIKACHU_CAUGHT]: 37,
  [Badge.UNIQUE_UNOWN]: 38,
  [Badge.DEX_GEN_2]: 39,
  [Badge.NORMAL_RAIDS_WON]: 40,
  [Badge.LEGENDARY_RAIDS_WON]: 41,
  [Badge.BERRIES_FED]: 42,
  [Badge.HOURS_DEFENDED]: 43,
  [Badge.DEX_GEN_3]: 45,
  [Badge.QUESTS]: 46,
  [Badge.BEST_FRIENDS]: 48,
  [Badge.TRADES]: 49,
  [Badge.TRADE_KM]: 50,
  [Badge.DEX_GEN_4]: 51,
  [Badge.LEAGUE_GREAT_WON]: 52,
  [Badge.LEAGUE_ULTRA_WON]: 53,
  [Badge.LEAGUE_MASTER_WON]: 54,
  [Badge.PHOTOBOMBS]: 55,
  [Badge.DEX_GEN_5]: 56,
  [Badge.PURIFIED]: 57,
  [Badge.GRUNTS_DEFEATED]: 58,
  [Badge.GIOVANNI_DEFEATED]: 59,
  [Badge.BEST_BUDDIES]: 60,
  [Badge.DEX_GEN_6]: 61,
  [Badge.DEX_GEN_7]: 62,
  [Badge.DEX_GEN_8]: 63,
  [Badge['seven_day_streaks']]: 64,
  [Badge.UNIQUE_RAID_BOSSES]: 65,
  [Badge.RAIDS_WITH_FRIENDS]: 66,
  [Badge.CAUGHT_AT_LURE]: 67,
  [Badge.WAYFARER_AGREEMENTS]: 68,
  [Badge.MEGA_EVOS]: 69,
  [Badge.UNIQUE_MEGA_EVOS]: 70,
  [Badge.TRAINERS_REFERRED]: 73,
  [Badge.RAID_ACHIEVEMENTS]: 76,
  [Badge.COLLECTIONS_DONE]: '1002_01',
  [Badge.CAUGHT_NORMAL]: 'ico_0_normal',
  [Badge.CAUGHT_FIGHTING]: 'ico_1_fighting',
  [Badge.CAUGHT_FLYING]: 'ico_2_flying',
  [Badge.CAUGHT_POISON]: 'ico_3_poison',
  [Badge.CAUGHT_GROUND]: 'ico_4_ground',
  [Badge.CAUGHT_ROCK]: 'ico_5_rock',
  [Badge.CAUGHT_BUG]: 'ico_6_bug',
  [Badge.CAUGHT_GHOST]: 'ico_7_ghost',
  [Badge.CAUGHT_STEEL]: 'ico_8_steel',
  [Badge.CAUGHT_FIRE]: 'ico_9_fire',
  [Badge.CAUGHT_WATER]: 'ico_10_water',
  [Badge.CAUGHT_GRASS]: 'ico_11_grass',
  [Badge.CAUGHT_ELECTRIC]: 'ico_12_electric',
  [Badge.CAUGHT_PSYCHIC]: 'ico_13_psychic',
  [Badge.CAUGHT_ICE]: 'ico_14_ice',
  [Badge.CAUGHT_DRAGON]: 'ico_15_dragon',
  [Badge.CAUGHT_DARK]: 'ico_16_dark',
  [Badge.CAUGHT_FAIRY]: 'ico_17_fairy',
};
